import * as THREE from 'three';
import * as xb from 'xrblocks';

/* MineD XR Blocks v2 · 2026-10-03 — 광석 이름을 axes.py 규칙과 일치, 웹 v4 payload 우선 사용 */
const FLOORS=[
{floor:'B1',year:2026,depth:'-18 m',label:'2024–2026',mineral:'호박',color:0xe0a93f,rock:0x5c4934,image:'../MineD_video_assets_v1/261003_MineD_C01_BEER_START_16x9_v2.png',action:'노을 아래에서 차가운 맥주 한 모금',evidence:'걸음 수 · 직전 52주 대비 상위 4%'},
{floor:'B2',year:2022,depth:'-42 m',label:'2020–2023',mineral:'형석',color:0x9fd8c8,rock:0x3d3545,image:'../MineD_video_assets_v1/261003_MineD_C04_END_C05_START_16x9_v1.png',action:'오래된 방갈로 안에서 기록과 머무르기',evidence:'메모 길이 하위 3% · 걸음 수 하위 6% · 2종 교차'},
{floor:'B3',year:2016,depth:'-73 m',label:'2011–2019',mineral:'황철석',color:0xc9b25a,rock:0x27343c,image:'../MineD_video_assets_v1/261003_MineD_C10_END_16x9_v1.png',action:'조개를 건네받은 가시복어와 교감하기',evidence:'걸음 수 · 직전 52주 대비 하위 4%'}];
try{const p=JSON.parse(localStorage.getItem('mineD.xrPayload')||'null');if(p&&p.raw_records_exported===false){const i=FLOORS.findIndex(f=>f.year===p.year);if(i>=0){if(p.mineral)FLOORS[i].mineral=p.mineral;if(p.asset)FLOORS[i].image=p.asset;if(p.scene)FLOORS[i].action=p.scene;if(Array.isArray(p.evidence))FLOORS[i].evidence=p.evidence.map(e=>e.join(' · ')).join(' / ');}}}catch(_){}

class FloorMineral extends xb.MeshScript{
constructor(index,data,world){super(new THREE.IcosahedronGeometry(.115,1),new THREE.MeshStandardMaterial({color:data.color,roughness:.64,metalness:.08,emissive:data.color,emissiveIntensity:.12}));this.index=index;this.data=data;this.world=world;this.name=`${data.year} ${data.mineral}`;this.position.set(.42,1.34-index*.48,-1.22)}
onObjectSelectStart(e){this.scale.setScalar(.9);e.stopPropagation()}
onObjectSelectEnd(e){this.scale.setScalar(1);if(e.completed)this.world.chooseOrMine(this.index);e.stopPropagation()}
dispose(){this.geometry.dispose();this.material.dispose()}}

class MineDStrataWorld extends xb.Script{
init(){
this.add(new THREE.HemisphereLight(0xe9e5dc,0x17222b,2.3));const key=new THREE.DirectionalLight(0xffd39a,2);key.position.set(-1.2,2.5,1.2);this.add(key);this.current=0;this.hits=0;this.elapsed=0;this.portal=null;this.textureLoader=new THREE.TextureLoader();this.shaft=new THREE.Group();
FLOORS.forEach((f,i)=>{const slab=new THREE.Mesh(new THREE.BoxGeometry(1.28,.12,.72),new THREE.MeshStandardMaterial({color:f.rock,roughness:.98}));slab.position.set(0,1.14-i*.48,-1.24);this.shaft.add(slab);for(let n=0;n<4;n++){const vein=new THREE.Mesh(new THREE.BoxGeometry(.12+.09*n,.012,.03),new THREE.MeshStandardMaterial({color:f.color,emissive:f.color,emissiveIntensity:.2,roughness:.6}));vein.position.set(-.46+n*.27,1.205-i*.48,-.86);this.shaft.add(vein)}});
const railMat=new THREE.MeshStandardMaterial({color:0x6b6253,roughness:.85});[-.22,.22].forEach(x=>{const r=new THREE.Mesh(new THREE.BoxGeometry(.025,1.42,.025),railMat);r.position.set(x,.92,-.96);this.shaft.add(r)});this.add(this.shaft);this.cabin=new THREE.Group();const frameMat=new THREE.MeshStandardMaterial({color:0x9b8b70,roughness:.75});const back=new THREE.Mesh(new THREE.BoxGeometry(.38,.32,.025),new THREE.MeshStandardMaterial({color:0x252b2f,roughness:.95}));back.position.z=-.03;this.cabin.add(back);[[0,.17,.38,.025],[0,-.17,.38,.025],[-.19,0,.025,.34],[.19,0,.025,.34]].forEach(([x,y,w,h])=>{const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,.035),frameMat);b.position.set(x,y,0);this.cabin.add(b)});this.cabin.position.set(0,1.4,-.94);this.add(this.cabin);
this.minerals=FLOORS.map((f,i)=>new FloorMineral(i,f,this));this.minerals.forEach(m=>this.add(m));this.keyHandler=e=>{const n=Number(e.key)-1;if(n>=0&&n<3)this.goFloor(n);if(e.key.toLowerCase()==='m'||e.key===' ')this.mine()};window.addEventListener('keydown',this.keyHandler);document.querySelectorAll('[data-floor]').forEach(b=>b.addEventListener('click',()=>this.goFloor(Number(b.dataset.floor))));document.querySelector('#mineButton').addEventListener('click',()=>this.mine());const requested=Number(new URLSearchParams(location.search).get('year'));let payload=null;try{payload=JSON.parse(localStorage.getItem('mineD.xrPayload')||'null')}catch{}const target=FLOORS.findIndex(f=>f.year===(requested||payload?.year));this.goFloor(target>=0?target:0,true)}
goFloor(index,initial=false){this.current=index;this.hits=0;this.removePortal();this.cabin.userData.targetY=1.4-index*.48;this.minerals.forEach((m,i)=>{m.material.emissiveIntensity=i===index?.5:.08;m.scale.setScalar(i===index?1.14:1)});document.querySelectorAll('[data-floor]').forEach((b,i)=>b.classList.toggle('on',i===index));const f=FLOORS[index];document.querySelector('#elevatorBadge').textContent=`${f.floor} · ${f.year} · ${f.depth}`;document.querySelector('#miningFill').style.width='0%';document.querySelector('#status').innerHTML=`<b>엘리베이터 ${f.floor} ${f.year}년 정차</b><br>${f.label} 지층의 ${f.mineral}이 보입니다. 광석을 세 번 핀치하거나 M을 눌러 캐세요.<small>${f.evidence} · 원본은 기기 밖으로 보내지 않음</small>`;if(!initial)this.cabin.rotation.z=.025}
chooseOrMine(index){if(index!==this.current){this.goFloor(index);return}this.mine()}
mine(){if(this.hits>=3)return;this.hits++;const m=this.minerals[this.current];m.rotation.z+=(this.hits%2?-.25:.25);m.scale.multiplyScalar(.88);setTimeout(()=>m.scale.setScalar(1.14),180);document.querySelector('#miningFill').style.width=`${this.hits/3*100}%`;if(this.hits===3){m.material.wireframe=true;setTimeout(()=>{m.material.wireframe=false;this.openEvidence(FLOORS[this.current])},260)}}
openEvidence(f){this.removePortal();const group=new THREE.Group();const frame=new THREE.Mesh(new THREE.BoxGeometry(.69,.42,.035),new THREE.MeshStandardMaterial({color:0x2b241b,roughness:.85}));const mat=new THREE.MeshBasicMaterial({color:0x273038});const screen=new THREE.Mesh(new THREE.PlaneGeometry(.64,.36),mat);screen.position.z=.02;group.add(frame,screen);this.textureLoader.load(f.image,t=>{t.colorSpace=THREE.SRGBColorSpace;mat.map=t;mat.color.setHex(0xffffff);mat.needsUpdate=true});group.position.set(-.18,1.18-this.current*.1,-.72);group.scale.setScalar(.02);this.portal=group;this.add(group);document.querySelector('#status').innerHTML=`<b>${f.year} ${f.mineral} 채굴 완료</b><br>${f.action}<small>${f.evidence}<br>광석 특징값 → MineD 장면 설계 → 실제 프로젝트 에셋 포털</small>`;document.querySelector('#assetBadge').textContent=`LIVE ASSET · ${f.image.split('/').pop()}`}
removePortal(){if(!this.portal){document.querySelector('#assetBadge').textContent='MINERAL LOCKED · 0/3';return}this.remove(this.portal);this.portal.traverse(n=>{n.geometry?.dispose();n.material?.dispose()});this.portal=null;document.querySelector('#assetBadge').textContent='MINERAL LOCKED · 0/3'}
update(delta){this.elapsed+=delta;const ty=this.cabin.userData.targetY??this.cabin.position.y;this.cabin.position.y=THREE.MathUtils.lerp(this.cabin.position.y,ty,Math.min(1,delta*3));this.cabin.rotation.z=THREE.MathUtils.lerp(this.cabin.rotation.z,0,Math.min(1,delta*4));this.minerals.forEach((m,i)=>{m.rotation.y+=delta*(.28+i*.06);m.position.y+=Math.sin(this.elapsed*1.2+i)*.0007});if(this.portal){const s=THREE.MathUtils.lerp(this.portal.scale.x,1,Math.min(1,delta*4));this.portal.scale.setScalar(s)}}
dispose(){window.removeEventListener('keydown',this.keyHandler);this.removePortal();this.minerals.forEach(m=>m.dispose());this.shaft.traverse(n=>{n.geometry?.dispose();n.material?.dispose()})}}

const options=new xb.Options();options.enableHands();options.hands.visualization=true;xb.add(new MineDStrataWorld());await xb.init(options);
